### ISSUE TITLE
[BUG]: mds-server becomes unresponsive

### ISSUE THREAD

**Issue by haasy** [mobile-directing-system/mds-server#48]
### Bug Description

After running a few hours the mds-server becomes unresponsive.

### Expected Behavior

The mds-server should never become unresponsive

### Steps to Reproduce

Let the mds-server run a few hours on windows with docker-desktop as backend.

### Further Information

[mds-server-errors.log](https://github.com/mobile-directing-system/mds-server/files/9049106/mds-server-errors.log)

**Comment by haasy** [comment]
i could replicate it on linux with minikube. It does not seem to be a specifically windows related issue. But it could still be minikube related.

**Comment by lefinal** [comment]
@haasy does the issue still persist?

**Comment by haasy** [comment]
No has not happened since the RAM upgrade in late July.
