### ISSUE TITLE
[BUG]: Retrieve All Groups doesn't work

### ISSUE THREAD

**Issue by haasy** [mobile-directing-system/mds-server#53]
### Bug Description

`GET /groups` always returns empty array, even if groups have been created. But `GET /groups/<group-id>` does work correctly.

### Expected Behavior

`GET /groups` returns available groups according to passed pagination parameters or default parameters. 

### Steps to Reproduce

1. create a group.
2. call `GET /groups`
3. response has empty entries array

**Comment by lefinal** [comment]
can't replicate. do you have the required permissions (_group.view_)?

**Comment by haasy** [comment]
I tried it with the admin user. Do users with administrator status additionally need this permission?

**Comment by haasy** [comment]
I deleted the my existing server, pulled the latest changes and rebuilt it. The problems with none of the existing groups being returned still persists. Both if the user has _admin_ status and if the user has the _group.view_ permission. When calling `GET /groups` the following response is returned:
```
{
  "total": 0,
  "limit": 20,
  "offset": 0,
  "ordered_by": null,
  "order_direction": "asc",
  "retrieved": 0,
  "entries": []
}
```
Even though the _mds-group-svc_ database has the following group entries:
```
mds-group-svc=# select * from groups;
                  id                  |    title    |                  description                   |              operation               
--------------------------------------+-------------+------------------------------------------------+--------------------------------------
 05fa6d25-a5e5-4da2-a610-9e3c2aaa36e8 | ils3khdjd1a | This is a Test Group with the name ils3khdjd1a | cd315867-0444-4297-817a-c7bef4aa5973
(1 row)
```
